### ISSUE TITLE
Ai đó hãy cứu vớt đời tuii

### ISSUE THREAD

**Issue by baonhu1304** [baonhu1304/Lop-10A2-nhom-1#17]
Nhức cái não quá dị mụi ngừi. Ai biết làm câu 3 hong gợi ý ii

**Comment by thaopham2501** [comment]
ũa câu hỏi là gì á :))) paste vô đây t xem thử

**Comment by baonhu1304** [comment]
Câu 3: Việc giải bài toán trên máy tính có giống như việc giải quyết vấn đề ngoài đời thực không? Cho 02 ví dụ. Nếu không, hãy tự tạo ra 3 bài toán có sử dụng những công thức toán đã được học. 
Nè nè.

**Comment by thaopham2501** [comment]
e mà thầy đánh giá tiến độ trễ rồi kìa :v năn nỉ thầy Hiền đẹp trai đọc được dòng này châm chước đi

**Comment by baonhu1304** [comment]
Thực sự khum mún trễ đâu Thầy oiiii ;0

**Comment by thaopham2501** [comment]
Vế đầu chắc là không rồi đó
còn tạo ra 3 bài toán thì làm kiểu tìm số lớn nhất, nhỏ nhất các thứ cho nó dễ ✌️

**Comment by thaopham2501** [comment]
> Thực sự khum mún trễ đâu Thầy oiiii ;0

**Comment by baonhu1304** [comment]
Ủa zạy sao thầy còn kiu cho 2 Vd nữa m

**Comment by thaopham2501** [comment]
còn giữ câu hỏi câu 4 không? paste lên t cái, để t xem @baonhu1304

**Comment by thaopham2501** [comment]
> Ủa zạy sao thầy còn kiu cho 2 Vd nữa m
lừa á :))) giỡn thoy, thầy còn có vế sau kìa, nếu không,...

**Comment by baonhu1304** [comment]
Câu 4: Từ ví dụ hoặc phép toán đã nêu, hãy mô tả bằng sơ đồ khối và liệt kê bước. Từ đó trình bày hoàn thiện đầy đủ các bước giải bài toán trên máy tính.
Đayyy

**Comment by thaopham2501** [comment]
ocey :vv

**Comment by baonhu1304** [comment]
zạy @letu25082006 làm 1 cái vd thui nhaaa

**Comment by letu25082006** [comment]
okok

**Comment by baonhu1304** [comment]
Ráng làm sớm nghen. Để tui lấy tui làm câu 4 <3 @letu25082006

**Comment by thaopham2501** [comment]
gòi t đi thiết kế cái bìa đây :))))))))) còn chỗ nào cấn nữa mọi người lên hỏi tiếp nha

**Comment by letu25082006** [comment]
@baonhu1304 ơi v tui ghi hết lên phần của tui hay sao á

**Comment by baonhu1304** [comment]
Uhhh

**Comment by baonhu1304** [comment]
@NguyenNgocNhuY  phân chia sao nèee

**Comment by NguyenNgocNhuY** [comment]
qua discussion nha @baonhu1304
