### ISSUE TITLE
I nít hép :((( não phẳng quá chả nghĩ ra cái sản phẩm nào ấn tượng

### ISSUE THREAD

**Issue by thaopham2501** [baonhu1304/Lop-10A2-nhom-1#20]

**Comment by Lenga10A2** [comment]
Đề là gì á

**Comment by thaopham2501** [comment]
> Đề là gì á
Tạo một sản phẩm ấn tượng từ sự ứng dụng của tin học.

**Comment by Lenga10A2** [comment]
1 sản phẩm ấn tượng ??? đề hỏi j ngộ v

**Comment by thaopham2501** [comment]
> 1 sản phẩm ấn tượng ??? đề hỏi j ngộ v

:>>>> khong biết, mà t nghĩ ra một cái, không biết thầy chấp nhận không :)))
