### ISSUE TITLE
mọi người cho tui hỏi "Bài toán" trong tin học có gì khác với lại giải thích tại sao nữa nha !!! Cảm ơn trước nè

### ISSUE THREAD

**Issue by Lenga10A2** [baonhu1304/Lop-10A2-nhom-1#4]

**Comment by Lenga10A2** [comment]
Ko hề lun nha lên gg search cx ko có lun á khóc thiệt chứ

Vào 20:59, T.4, 13 Th10, 2021 Phạm Ngọc Hương Thảo ***@***.***>
đã viết:

**Comment by Lenga10A2** [comment]
Quàooo then kiu


Vào 21:38, T.4, 13 Th10, 2021 Phạm Ngọc Hương Thảo ***@***.***>
đã viết:

**Comment by thaopham2501** [comment]
Trong các yêu cầu sau, yêu cầu nào được xem là bài toán: giải phương trình ax2+bx+c=0; In một dòng chữ ra màn hình, tìm ước chung lớn nhất của 2 số nguyên dương a, b; tra cứu một từ trong từ điển; tính diện tích hình tròn? Vậy khái niệm "Bài toán" trong Tin học có khác gì không? 
này là đề phớ hôn? thì bài toán trong tin học gồm tất cả các cái trên luôn chứ không chỉ là tính toán nữa

**Comment by thaopham2501** [comment]
phải mà? giờ cho máy tính cái thông tin đó là một từ nào đó, thì nó cho mình kết quả? :')
