### ISSUE TITLE
Mn giúp tui vế 2 câu 4 với nha!!! 

### ISSUE THREAD

**Issue by NguyenNgocNhuY** [baonhu1304/Lop-10A2-nhom-1#8]

**Comment by thaopham2501** [comment]
Bước 1. Xóa bảng; 

Bước 2. Vẽ tam giác; 

Bước 2. Nếu tam giác có góc bằng 90 độ thì kết thúc; 

Bước 4. Quay lại bước 1; 
:))) chép đề y chang  :v

**Comment by NguyenNgocNhuY** [comment]
tui cũng nghĩ vậy mà thấy nó giống ở trên nên thấy kì kì
